const weatherData = [
  'Cloud development not observed or not observable',
  'Clouds generally dissolving or becoming less developed',
  'State of sky on the whole unchanged',
  'Clouds generally forming or developing',
  'Visibility reduced by smoke',
  'Haze',
  'Widespread dust in suspension in the air',
  'Dust or sand raised by wind',
  'Well developed dust whirls or sand whirls seen',
  'Duststorm or sandstorm within sight',
  'Mist',
  'Patches of shallow fog or ice fog',
  'More or less continuous fog',
  'Lightning visible, no thunder heard',
  'Precipitation within sight, not reaching the ground or surface of the sea',
  'Precipitation within sight, reaching the ground or surface of the sea, but distant',
  'Precipitation within sight, reaching the ground or surface of the sea, near to, but not at the station',
  'Thunderstorm, but no precipitation',
  'Squalls at or within sight of the station',
  'Funnel cloud(s)',
  'Drizzle or snow grains, not falling as showers',
  'Rain, not freezing',
  'Snow',
  'Rain and snow or ice pellets',
  'Freezing drizzle or freezing rain',
  'Showers of rain',
  'Showers of snow or rain and snow',
  'Showers of hail or rain and hail',
  'Fog or ice fog',
  'Thunderstorm (with or without precipitation)',
  'Slight or moderate duststorm or sandstorm (decreased during the preceding hour)',
  'No appreciable change in duststorm or sandstorm during the preceding hour',
  'Duststorm or sandstorm began or increased during the preceding hour',
  'Severe duststorm or sandstorm (decreased during the preceding hour)',
  'No appreciable change in severe duststorm or sandstorm during the preceding hour',
  'Severe duststorm or sandstorm began or increased during the preceding hour',
  'Slight or moderate blowing snow (generally low)',
  'Heavy drifting snow',
  'Slight or moderate blowing snow (generally high)',
  'Heavy drifting snow',
  'Fog or ice fog at a distance, extending to a level above the observer',
  'Fog or ice fog in patches',
  'Fog or ice fog, sky visible (thinner during the preceding hour)',
  'Fog or ice fog, sky invisible',
  'Fog or ice fog, sky visible (no appreciable change during the preceding hour)',
  'Fog or ice fog, sky invisible',
  'Fog or ice fog, sky visible (thicker during the preceding hour)',
  'Fog or ice fog, sky invisible',
  'Fog depositing rime, sky visible',
  'Fog depositing rime, sky invisible',
  'Drizzle, not freezing, intermittent (slight at time of observation)',
  'Drizzle, not freezing, continuous',
  'Drizzle, not freezing, intermittent (moderate at time of observation)',
  'Drizzle, not freezing, continuous',
  'Drizzle, not freezing, intermittent (heavy at time of observation)',
  'Drizzle, not freezing, continuous',
  'Drizzle, freezing, slight',
  'Drizzle, freezing, moderate or heavy',
  'Drizzle and rain, slight',
  'Drizzle and rain, moderate or heavy',
  'Rain, not freezing, intermittent (slight at time of observation)',
  'Rain, not freezing, continuous',
  'Rain, not freezing, intermittent (moderate at time of observation)',
  'Rain, not freezing, continuous',
  'Rain, not freezing, intermittent (heavy at time of observation)',
  'Rain, not freezing, continuous',
  'Rain, freezing, slight',
  'Rain, freezing, moderate or heavy',
  'Rain or drizzle and snow, slight',
  'Rain or drizzle and snow, moderate or heavy',
  'Intermittent fall of snowflakes, slight at time of observation',
  'Continuous fall of snowflakes',
  'Intermittent fall of snowflakes, moderate at time of observation',
  'Continuous fall of snowflakes',
  'Intermittent fall of snowflakes, heavy at time of observation',
  'Continuous fall of snowflakes',
  'Diamond dust (with or without fog)',
  'Snow grains (with or without fog)',
  'Isolated star-like snow crystals (with or without fog)',
  'Ice pellets',
  'Rain showers, slight',
  'Rain showers, moderate or heavy',
  'Rain showers, violent',
  'Showers of rain and snow mixed, slight',
  'Showers of rain and snow mixed, moderate or heavy',
  'Snow showers, slight',
  'Snow showers, moderate or heavy',
  'Showers of snow pellets or small hail, with or without rain or rain and snow mixed (slight)',
  'Showers of snow pellets or small hail, with or without rain or rain and snow mixed (moderate or heavy)',
  'Showers of hail, with or without rain or rain and snow mixed, not associated with thunder (slight)',
  'Showers of hail, with or without rain or rain and snow mixed, not associated with thunder (moderate or heavy)',
  'Slight rain at time of observation, thunderstorm during the preceding hour but not at time of observation',
  'Moderate or heavy rain at time of observation',
  'Slight snow, or rain and snow mixed or hail at time of observation',
  'Moderate or heavy snow, or rain and snow mixed or hail at time of observation',
  'Thunderstorm, slight or moderate, without hail but with rain and/or snow at time of observation (thunderstorm at time of observation)',
  'Thunderstorm, slight or moderate, with hail at time of observation',
  'Thunderstorm, heavy, without hail but with rain and/or snow at time of observation',
  'Thunderstorm combined with duststorm or sandstorm at time of observation',
  'Thunderstorm, heavy, with hail at time of observation',
];

export default weatherData;
