const weatherData = {
  '00': 'Cloud development not observed or not observable',
  '01': 'Clouds generally dissolving or becoming less developed',
  '02': 'State of sky on the whole unchanged',
  '03': 'Clouds generally forming or developing',
  '04': 'Visibility reduced by smoke',
  '05': 'Haze',
  '06': 'Widespread dust in suspension in the air',
  '07': 'Dust or sand raised by wind',
  '08': 'Well developed dust whirls or sand whirls seen',
  '09': 'Duststorm or sandstorm within sight',
  '10': 'Mist',
  '11': 'Patches of shallow fog or ice fog',
  '12': 'More or less continuous fog',
  '13': 'Lightning visible, no thunder heard',
  '14': 'Precipitation within sight, not reaching the ground or surface of the sea',
  '15': 'Precipitation within sight, reaching the ground or surface of the sea, but distant',
  '16': 'Precipitation within sight, reaching the ground or surface of the sea, near to, but not at the station',
  '17': 'Thunderstorm, but no precipitation',
  '18': 'Squalls at or within sight of the station',
  '19': 'Funnel cloud(s)',
  '20': 'Drizzle or snow grains, not falling as showers',
  '21': 'Rain, not freezing',
  '22': 'Snow',
  '23': 'Rain and snow or ice pellets',
  '24': 'Freezing drizzle or freezing rain',
  '25': 'Showers of rain',
  '26': 'Showers of snow or rain and snow',
  '27': 'Showers of hail or rain and hail',
  '28': 'Fog or ice fog',
  '29': 'Thunderstorm (with or without precipitation)',
  '30': 'Slight or moderate duststorm or sandstorm (decreased during the preceding hour)',
  '31': 'No appreciable change in duststorm or sandstorm during the preceding hour',
  '32': 'Duststorm or sandstorm began or increased during the preceding hour',
  '33': 'Severe duststorm or sandstorm (decreased during the preceding hour)',
  '34': 'No appreciable change in severe duststorm or sandstorm during the preceding hour',
  '35': 'Severe duststorm or sandstorm began or increased during the preceding hour',
  '36': 'Slight or moderate blowing snow (generally low)',
  '37': 'Heavy drifting snow',
  '38': 'Slight or moderate blowing snow (generally high)',
  '39': 'Heavy drifting snow',
  '40': 'Fog or ice fog at a distance, extending to a level above the observer',
  '41': 'Fog or ice fog in patches',
  '42': 'Fog or ice fog, sky visible (thinner during the preceding hour)',
  '43': 'Fog or ice fog, sky invisible',
  '44': 'Fog or ice fog, sky visible (no appreciable change during the preceding hour)',
  '45': 'Fog or ice fog, sky invisible',
  '46': 'Fog or ice fog, sky visible (thicker during the preceding hour)',
  '47': 'Fog or ice fog, sky invisible',
  '48': 'Fog depositing rime, sky visible',
  '49': 'Fog depositing rime, sky invisible',
  '50': 'Drizzle, not freezing, intermittent (slight at time of observation)',
  '51': 'Drizzle, not freezing, continuous',
  '52': 'Drizzle, not freezing, intermittent (moderate at time of observation)',
  '53': 'Drizzle, not freezing, continuous',
  '54': 'Drizzle, not freezing, intermittent (heavy at time of observation)',
  '55': 'Drizzle, not freezing, continuous',
  '56': 'Drizzle, freezing, slight',
  '57': 'Drizzle, freezing, moderate or heavy',
  '58': 'Drizzle and rain, slight',
  '59': 'Drizzle and rain, moderate or heavy',
  '60': 'Rain, not freezing, intermittent (slight at time of observation)',
  '61': 'Rain, not freezing, continuous',
  '62': 'Rain, not freezing, intermittent (moderate at time of observation)',
  '63': 'Rain, not freezing, continuous',
  '64': 'Rain, not freezing, intermittent (heavy at time of observation)',
  '65': 'Rain, not freezing, continuous',
  '66': 'Rain, freezing, slight',
  '67': 'Rain, freezing, moderate or heavy',
  '68': 'Rain or drizzle and snow, slight',
  '69': 'Rain or drizzle and snow, moderate or heavy',
  '70': 'Intermittent fall of snowflakes, slight at time of observation',
  '71': 'Continuous fall of snowflakes',
  '72': 'Intermittent fall of snowflakes, moderate at time of observation',
  '73': 'Continuous fall of snowflakes',
  '74': 'Intermittent fall of snowflakes, heavy at time of observation',
  '75': 'Continuous fall of snowflakes',
  '76': 'Diamond dust (with or without fog)',
  '77': 'Snow grains (with or without fog)',
  '78': 'Isolated star-like snow crystals (with or without fog)',
  '79': 'Ice pellets',
  '80': 'Rain showers, slight',
  '81': 'Rain showers, moderate or heavy',
  '82': 'Rain showers, violent',
  '83': 'Showers of rain and snow mixed, slight',
  '84': 'Showers of rain and snow mixed, moderate or heavy',
  '85': 'Snow showers, slight',
  '86': 'Snow showers, moderate or heavy',
  '87': 'Showers of snow pellets or small hail, with or without rain or rain and snow mixed (slight)',
  '88': 'Showers of snow pellets or small hail, with or without rain or rain and snow mixed (moderate or heavy)',
  '89': 'Showers of hail, with or without rain or rain and snow mixed, not associated with thunder (slight)',
  '90': 'Showers of hail, with or without rain or rain and snow mixed, not associated with thunder (moderate or heavy)',
  '91': 'Slight rain at time of observation, thunderstorm during the preceding hour but not at time of observation',
  '92': 'Moderate or heavy rain at time of observation',
  '93': 'Slight snow, or rain and snow mixed or hail at time of observation',
  '94': 'Moderate or heavy snow, or rain and snow mixed or hail at time of observation',
  '95': 'Thunderstorm, slight or moderate, without hail but with rain and/or snow at time of observation (thunderstorm at time of observation)',
  '96': 'Thunderstorm, slight or moderate, with hail at time of observation',
  '97': 'Thunderstorm, heavy, without hail but with rain and/or snow at time of observation',
  '98': 'Thunderstorm combined with duststorm or sandstorm at time of observation',
  '99': 'Thunderstorm, heavy, with hail at time of observation',
};

export default weatherData;
